/*
===============================================================================
 File        : FilterChip.cs
 Namespace   : AbsenceApp.Client.Shared
 Author      : Michael
 Version     : 1.0.0
 Created     : 2026-03-17
 Updated     : 2026-03-17
-------------------------------------------------------------------------------
 Purpose     : Immutable record representing a single active filter chip
               displayed below the filter dropdowns in TablePageTemplate.
               Each chip carries a display label (Name), the selected value
               (Value), and a stable unique Id used for safe list removal.
-------------------------------------------------------------------------------
 Notes       :
   - Id is generated by the constructor so callers do not need to supply it.
   - The record is sealed to prevent unintended inheritance.
   - Equality is structural (record default): two chips with the same Name
     and Value but different Ids are NOT equal — enabling duplicate filter
     values for different filter categories.
-------------------------------------------------------------------------------
 Changes     :
   - 1.0.0  2026-03-17  Initial implementation.
===============================================================================
*/

namespace AbsenceApp.Client.Shared;

/// <summary>
/// Represents one active filter chip in <see cref="TablePageTemplate"/>.
/// </summary>
public sealed record FilterChip
{
    // =========================================================================
    // Properties
    // =========================================================================

    /// <summary>Unique key used for stable removal from the active-filters list.</summary>
    public string Id    { get; init; }

    /// <summary>Filter category label shown on the chip (e.g. "Year Group").</summary>
    public string Name  { get; init; }

    /// <summary>Selected value shown on the chip (e.g. "Year 10").</summary>
    public string Value { get; init; }

    // =========================================================================
    // Constructor — auto-assigns a unique Id
    // =========================================================================

    public FilterChip(string name, string value)
    {
        Id    = Guid.NewGuid().ToString("N");
        Name  = name;
        Value = value;
    }
}
