/*
===============================================================================
 File        : TableSettingsDiagnosticDto.cs
 Namespace   : AbsenceApp.Core.DTOs
 Author      : Michael
 Version     : 1.0.0
 Created     : 2026-03-17
 Updated     : 2026-03-17
-------------------------------------------------------------------------------
 Purpose     : DTOs returned by ITableSettingsService.GetDiagnosticsAsync().
               Used by the admin diagnostic page to surface schema drift,
               orphaned saved settings, and unmapped EF entities.
===============================================================================
*/

namespace AbsenceApp.Core.DTOs;

/// <summary>
/// Diagnostic data for one Table Settings page.
/// </summary>
public class PageTableSettingsDiagnosticDto
{
    /// <summary>The page key used in TableOptions and PageEntityMap (e.g. "students").</summary>
    public string PageKey { get; init; } = "";

    /// <summary>The CLR type name of the mapped EF entity (e.g. "Student").</summary>
    public string EntityTypeName { get; init; } = "";

    /// <summary>True when PageEntityMap has a valid EF entity type for this page key.</summary>
    public bool HasEntityMapping { get; init; }

    /// <summary>All fields derived from EF Core metadata for this entity (snake_case).</summary>
    public IReadOnlyList<string> SchemaFields { get; init; } = [];

    /// <summary>All field names that have a saved row in table_page_settings for this page.</summary>
    public IReadOnlyList<string> SavedFields { get; init; } = [];

    /// <summary>
    /// Schema fields with no saved settings row — these get schema-driven defaults. Informational only.
    /// </summary>
    public IReadOnlyList<string> UnsavedSchemaFields { get; init; } = [];

    /// <summary>
    /// Saved DB rows for fields that no longer exist in the schema (stale/orphaned).
    /// These are silently dropped by GetSettingsAsync but represent schema drift.
    /// </summary>
    public IReadOnlyList<string> OrphanedSavedFields { get; init; } = [];

    /// <summary>OK, Warning (orphaned saved fields), or Error (no entity mapping found).</summary>
    public string Status { get; init; } = "OK";
}

/// <summary>
/// Full diagnostic report for all Table Settings pages, generated by
/// ITableSettingsService.GetDiagnosticsAsync().
/// </summary>
public class TableSettingsDiagnosticReport
{
    /// <summary>One entry per mapped page key in PageEntityMap.</summary>
    public IReadOnlyList<PageTableSettingsDiagnosticDto> Pages { get; init; } = [];

    /// <summary>
    /// Distinct page names found in table_page_settings whose pageName is
    /// not present in PageEntityMap. These rows can never be loaded.
    /// </summary>
    public IReadOnlyList<string> OrphanedDbPageKeys { get; init; } = [];

    /// <summary>
    /// EF entity CLR type names registered in AppDbContext that have no
    /// corresponding Table Settings page mapping. Informational only.
    /// </summary>
    public IReadOnlyList<string> UnmappedEntityTypes { get; init; } = [];

    /// <summary>UTC timestamp of when this report was generated.</summary>
    public DateTime GeneratedAt { get; init; } = DateTime.UtcNow;

    /// <summary>OK, Warning, or Error — rolled up from all pages and orphaned rows.</summary>
    public string OverallStatus { get; init; } = "OK";
}
